# Generated by Django 3.2.5 on 2021-07-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_alter_contactmessage_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='contactmessage',
            unique_together={('name', 'phone')},
        ),
    ]
