# Generated by Django 3.2.5 on 2021-07-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_auto_20210710_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'category')},
        ),
    ]
