# Generated by Django 3.2.5 on 2021-07-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_auto_20210710_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
