# Generated by Django 3.2.5 on 2021-07-10 19:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_alter_product_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uses',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
