# Generated by Django 3.2.5 on 2021-07-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_auto_20210711_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'content')},
        ),
    ]
