# Generated by Django 3.2.5 on 2021-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_alter_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
