# Generated by Django 3.2.5 on 2021-07-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_alter_product_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='anyoffers',
            field=models.BooleanField(default=False),
        ),
    ]
